// Test generated by RoostGPT for test go-test using AI Model gpt

package main

import (
	"fmt"
	"testing"
	"time"
)

type Article struct {
	PublishedAt time.Time
}

func (a *Article) FormatPublishedDate() string {
	year, month, day := a.PublishedAt.Date()
	return fmt.Sprintf("%v %d, %d", month, day, year)
}

func TestFormatPublishedDateab8fb4dd88(t *testing.T) {
	// Test case 1: Check the formatted date for a valid date
	article := &Article{PublishedAt: time.Date(2020, 5, 1, 0, 0, 0, 0, time.UTC)}
	expected := "May 1, 2020"
	if result := article.FormatPublishedDate(); result != expected {
		t.Errorf("Expected '%s', got '%s'", expected, result)
	}

	// Test case 2: Check the formatted date for a leap year date
	article = &Article{PublishedAt: time.Date(2020, 2, 29, 0, 0, 0, 0, time.UTC)}
	expected = "February 29, 2020"
	if result := article.FormatPublishedDate(); result != expected {
		t.Errorf("Expected '%s', got '%s'", expected, result)
	}
}
