// Test generated by RoostGPT for test go-test using AI Model gpt

package main

import (
	"net/http"
	"net/http/httptest"
	"os"
	"testing"
)

func TestMaincfede2155b(t *testing.T) {
	// Test case 1: When API_KEY is not set in environment
	os.Setenv("API_KEY", "")
	request, _ := http.NewRequest("GET", "/", nil)
	response := httptest.NewRecorder()
	main()
	if status := response.Code; status != http.StatusInternalServerError {
		t.Errorf("handler returned wrong status code: got %v want %v",
			status, http.StatusInternalServerError)
	}

	// Test case 2: When PORT is not set in environment
	os.Setenv("API_KEY", "dummykey")
	os.Setenv("PORT", "")
	request, _ = http.NewRequest("GET", "/", nil)
	response = httptest.NewRecorder()
	main()
	if status := response.Code; status != http.StatusOK {
		t.Errorf("handler returned wrong status code: got %v want %v",
			status, http.StatusOK)
	}

	// Test case 3: When both API_KEY and PORT are set in environment
	os.Setenv("API_KEY", "dummykey")
	os.Setenv("PORT", "8080")
	request, _ = http.NewRequest("GET", "/", nil)
	response = httptest.NewRecorder()
	main()
	if status := response.Code; status != http.StatusOK {
		t.Errorf("handler returned wrong status code: got %v want %v",
			status, http.StatusOK)
	}
}
